#!/bin/ksh
for i in *.cbl
   do
     echo $i
     echo $i | tr '[a-z]' '[A-Z]'
     #b=_toupper($i)
     #b='EL690S.BMS'
     #echo $b
     #cp $i $b
     mv $i `echo $i | tr '[a-z]' '[A-Z]'`
     #mv -i "$i" 'echo "$i" | tr '[a-z]' '[A-Z]''
   done
