#!/bin/ksh
$indir = "/apps/test/cid1t/src/batch"
chdir($indir)
for i in *T.cbl
   do
    echo got $i
     $t = $i
     $i =~ s/T\./\./
     about to diff $i
#     diff /apps/prod/cid1p/src/batch/$i /apps/test/cid1t/src/batch/$t > "$t"."diff"
   print("Press Enter to Continue"); <stdin>;
   done
print("Press Enter to End"); <stdin>;
