rem Script file generated by user 
rem
rem Date created: Wed Sep 12 15:19:20 2001
rem
rem
e:/cid1p/convdata/exe/a2e_elchkq.exe -l e:/cid1p/convdata/cntl/a2e_elchkq.err -r e:/cid1p/sys/elchkq.txt -d e:/inetpub/ftproot/peer_logic/elchkq.txt -s e:/cid1p/convdata/cntl/a2e_elchkq.sta -i -f   -c a2e 
@echo Converted data written to e:/inetpub/ftproot/peer_logic/elchkq.txt
@echo Record statistics written to e:/cid1p/convdata/cntl/a2e_elchkq.sta
@echo Error messages written to e:/cid1p/convdata/cntl/a2e_elchkq.err
