#!/bin/ksh
for i in *.CBL
   do
     echo $i
     echo $i | sed 's/CBL$/cbl/'
     #echo $i | tr '(CL2)$' '(cl2)'
     #b=_toupper($i)
     #b='EL690S.BMS'
     #echo $b
     #cp $i $b
     mv $i `echo $i | sed 's/CBL$/cbl/'`
     #mv -i "$i" 'echo "$i" | tr '[a-z]' '[A-Z]''
   done
