$filein = $ARGV[0];
$fileot = $ARGV[1];
open(COMMIN,"$filein") || die "Open in failed on $filein: $!";
open(COMMOT, ">$fileot") || die "Open out failed on $fileot: $!";
$in_temp = "A56 A13 A11 A9 A6 A11 A172 A11 A11 A10 A10 A8 A3 A11 A11 A70 A52 A7";
$spaces = "     ";
while (<COMMIN>) {
   chomp($in_rec = $_);
   @fld_array = split /","/;
#   @fields = unpack($in_temp, $in_rec);
   print ($fld_array[0]);
#   $fld_array[2] =~ s/\.//;
#   $fld_array[3] =~ s/\.//;
#   $fld_array[5] =~ s/\.//;
#   $fld_array[7] =~ s/\.//;
#   $fld_array[8] =~ s/\.//;
#   $fld_array[9] =~ s/\.//;
#   $fld_array[10] =~ s/\.//;
#   $fld_array[11] =~ s/\.//;
#   $fld_array[13] =~ s/\.//;
#   $fld_array[14] =~ s/\.//;
#   $fld_array[15] =~ s/\.//;
#   $fld_array[16] =~ s/\.//;
#   $fld_array[17] =~ s/\.//;
#   $fld_array[18] =~ s/\.//;
#   $fld_array[19] =~ s/\.//;
#   $fld_array[20] =~ s/\.//;
#   $fld_array[21] =~ s/\.//;
#   $fld_array[22] =~ s/\.//;
#   $fld_array[23] =~ s/\.//;
#   $fld_array[24] =~ s/\.//;
#   $fld_array[25] =~ s/\.//;
#   $fld_array[26] =~ s/\.//;
#   $fld_array[27] =~ s/\.//;
#   $fld_array[28] =~ s/\.//;
#   $fld_array[29] =~ s/\.//;
#   $fld_array[30] =~ s/\.//;
#   $fld_array[31] =~ s/\.//;
#   $fld_array[32] =~ s/\.//;
#   $fld_array[33] =~ s/\.//;
#   $fld_array[34] =~ s/\.//;
#   $fld_array[35] =~ s/\.//;
#   $fld_array[36] =~ s/\.//;
#   $fld_array[37] =~ s/\.//;
#   $fld_array[38] =~ s/\.//;
#   $fld_array[39] =~ s/\.//;
   printf COMMOT "%15s%10s%10s%9s%6s%15s%10s%1s%30s%30s%30s%2s%9s%10s%17s%11s%6s%15s%10s%1s%65s%20s%20s%20s%20s%20s%20s%20s%20s%20s%20s%20s%20s%20s%20s%20s%20s%20s%20s\n", @fld_array, $spaces;
}
close COMMOT;
close COMMIN;
#print("Press Enter to End"); <stdin>;
